import { LayoutSchema, ComponentNode, BindingExpression } from '../types/schema';

function resolvePath(path: string, obj: any) {
  return path.split('.').reduce((acc: any, key: string) => acc?.[key], obj);
}

export function resolveBinding(
  expression: BindingExpression,
  data: Record<string, any>
): string {
  if (typeof expression !== 'string') return String(expression);

  return expression.replace(/\{\{(.+?)\}\}/g, (_, path) => {
    const value = resolvePath(path.trim(), data);
    return value !== undefined ? String(value) : `{{${path}}}`;
  });
}

function renderComponent(
  component: ComponentNode,
  data: Record<string, any>
): string {
  const content = (component as any).content 
    ? resolveBinding((component as any).content, data) 
    : '';

  const commonStyle = (c: any) => {
    const align = c.align || 'left';
    const weight = c.style?.fontWeight === 'bold' ? 'bold' : 'regular';
    const size = c.style?.fontSize || 10;
    return { align, weight, size };
  };

  switch (component.type) {
    case 'text': {
      const { align, weight, size } = commonStyle(component);
      return `#set align(${align})\n#text(size: ${size}pt, weight: "${weight}")[${content.replace(/\n/g, ' \n ')}]\n`;
    }

    case 'line':
      return `#line(length: 100%, stroke: ${(component as any).thickness || '1pt'} + ${(component as any).color || 'black'})\n`;

    case 'spacer':
      return `#v(${(component as any).height})\n`;

    case 'image':
      return `#image("${(component as any).src}", width: ${(component as any).width || 'auto'})\n`;

    case 'barcode':
    case 'qr': {
      const label = component.type === 'barcode' ? 'BARCODE' : 'QR CODE';
      const val = resolveBinding((component as any).value || '12345678', data);
      return `#rect(width: 3cm, height: 1cm, stroke: 1pt + black, fill: gray.lighten(90%))[
        #set align(center + horizon)
        #text(size: 8pt, weight: "bold")[${label}]\n
        #text(size: 6pt)[${val}]
      ]\n`;
    }

    case 'table': {
      const tableComp = component as any;
      let tableTypst = '#table(\n  columns: (';
      tableTypst += tableComp.columns.map((c: any) => (c.width || '1fr').replace('*', 'fr')).join(', ') + '),\n';
      tableTypst += '  inset: 7pt,\n  align: horizon,\n  stroke: 0.5pt + gray,\n';
      
      // Header
      if (tableComp.showHeader) {
        tableTypst += '  fill: (x, y) => if y == 0 { blue.lighten(90%) },\n';
        tableTypst += '  ' + tableComp.columns.map((c: any) => `[*${c.header}*]`).join(', ') + ',\n';
      }

      // Rows
      const path = tableComp.dataSource.replace(/\{\{(.+?)\}\}/g, '$1').trim();
      const items = (resolvePath(path, data) as any[]) || [];
      
      items.forEach(item => {
        tableTypst += '  ' + tableComp.columns.map((c: any) => {
          const val = resolvePath(c.field, item);
          return `[${val !== undefined ? val : ''}]`;
        }).join(', ') + ',\n';
      });

      tableTypst += ')\n';
      return tableTypst;
    }

    default:
      return `\n// Unsupported component: ${component.type}\n`;
  }
}

export function schemaToTypst(
  schema: LayoutSchema,
  data: Record<string, any>
): string {
  let typst = `// AUTO-GENERATED BY TYPSTFLOW\n`;
  
  // Page Setup
  const { page } = schema;
  typst += `#set page(\n`;
  typst += `  paper: "${page.size.toLowerCase()}",\n`;
  typst += `  flipped: ${page.orientation === 'landscape'},\n`;
  typst += `  margin: (top: ${page.margin.top}, bottom: ${page.margin.bottom}, left: ${page.margin.left}, right: ${page.margin.right}),\n`;
  typst += `)\n`;

  // Default font
  const mainFont = schema.fonts.find(f => f.role === 'body') || schema.fonts[0];
  if (mainFont) {
    typst += `#set text(font: "${mainFont.family}", size: ${mainFont.size}pt, lang: "th")\n\n`;
  }

  // Render Header Zone
  if (schema.zones.header.components.length > 0) {
    typst += `// --- Header ---\n`;
    schema.zones.header.components.forEach(comp => {
      typst += renderComponent(comp, data);
    });
  }

  // Render Body Zone
  typst += `\n// --- Body ---\n`;
  schema.zones.body.components.forEach(comp => {
    typst += renderComponent(comp, data);
  });

  // Render Footer Zone
  if (schema.zones.footer.components.length > 0) {
    typst += `\n// --- Footer ---\n`;
    schema.zones.footer.components.forEach(comp => {
      typst += renderComponent(comp, data);
    });
  }

  return typst;
}
