import type { LayoutSchema } from '../../types/schema';

export const INVOICE_WITH_PAGE_BREAKS_TEMPLATE: LayoutSchema = {
  id: 'professional-invoice-with-breaks',
  name: 'Professional Invoice (Page Breaks)',
  version: '1.0.0',
  page: {
    size: 'A4',
    orientation: 'portrait',
    margin: { top: '15mm', bottom: '15mm', left: '15mm', right: '15mm' },
  },
  fonts: [{ family: 'Sarabun', role: 'body', size: 10, embedded: true }],
  zones: {
    header: {
      id: 'header',
      minHeight: '35mm',
      showOnFirstPageOnly: true,
      components: [
        {
          id: 'logo',
          type: 'text',
          content: 'TYPSTFLOW',
          x: 0,
          y: 0,
          width: 70,
          height: 12,
          style: { fontSize: 26, fontWeight: 'bold', color: '#1e40af' }, // Deep Royal Blue
          align: 'left',
        },
        {
          id: 'company-name',
          type: 'text',
          content: 'บริษัท ไทยเทค โซลูชั่นส์ จำกัด',
          x: 0,
          y: 13,
          width: 100,
          height: 6,
          style: { fontSize: 13, fontWeight: 'bold', color: '#1e293b' },
          align: 'left',
        },
        {
          id: 'company-address',
          type: 'text',
          content: '123 ถนนสุขุมวิท แขวงคลองเตย เขตคลองเตย กรุงเทพฯ 10110',
          x: 0,
          y: 20,
          width: 120,
          height: 5,
          style: { fontSize: 8.5, color: '#475569' },
          align: 'left',
        },
        {
          id: 'invoice-title',
          type: 'text',
          content: 'INVOICE',
          x: 120,
          y: 0,
          width: 60,
          height: 10,
          style: { fontSize: 32, fontWeight: 'bold', color: '#1e293b' },
          align: 'right',
        },
        {
          id: 'invoice-number',
          type: 'text',
          content: 'เลขที่: {{invoice.number}}',
          x: 120,
          y: 12,
          width: 60,
          height: 5,
          style: { fontSize: 10, fontWeight: 'bold', color: '#1e293b' },
          align: 'right',
        },
        {
          id: 'invoice-date',
          type: 'text',
          content: 'วันที่: {{invoice.date}}',
          x: 120,
          y: 17,
          width: 60,
          height: 5,
          style: { fontSize: 10, color: '#64748b' },
          align: 'right',
        },
        {
          id: 'header-line',
          type: 'line',
          x: 0,
          y: 30,
          width: 180,
          height: 1,
          thickness: '1.5pt',
          color: '#1e40af',
        },
      ],
    },
    footer: {
      id: 'footer',
      minHeight: '20mm',
      showOnLastPageOnly: false,
      components: [
        {
          id: 'footer-line',
          type: 'line',
          x: 0,
          y: 2,
          width: 180,
          height: 1,
          thickness: '0.5pt',
          color: '#cbd5e1',
        },
        {
          id: 'thank-you',
          type: 'text',
          content: 'Thank you for your business!',
          x: 0,
          y: 5,
          width: 180,
          height: 5,
          style: { fontSize: 10, fontWeight: 'medium', color: '#1e40af' },
          align: 'center',
        },
        {
          id: 'contact-info',
          type: 'text',
          content:
            'Thai Tech Solutions Co., Ltd. | Tel: 02-123-4567 | Email: accounting@thaitech.co.th',
          x: 0,
          y: 12,
          width: 180,
          height: 4,
          style: { fontSize: 7, color: '#94a3b8' },
          align: 'center',
        },
      ],
    },
  },
  pages: [
    {
      id: 'page-1',
      name: 'Invoice Main',
      body: {
        id: 'body',
        minHeight: '150mm',
        components: [
          // Customer Information Section
          {
            id: 'customer-section',
            type: 'text',
            content:
              'BILL TO\n\n{{invoice.customer.name}}\n{{invoice.customer.address}}\nTax ID: {{invoice.customer.tax_id}}',
            x: 0,
            y: 0,
            width: 180,
            height: 30,
            style: { fontSize: 10, lineHeight: 1.5, color: '#1e293b' },
            align: 'left',
          },

          // Products Table
          {
            id: 'products-table',
            type: 'table',
            dataSource: '{{invoice.items}}',
            x: 0,
            y: 35,
            width: 180,
            height: 120,
            pageBreakBefore: false,
            showHeader: true,
            repeatHeaderOnPage: true,
            columns: [
              {
                id: 'col1',
                header: 'รายการ (Description)',
                field: 'description',
                width: '3fr',
                align: 'left',
              },
              { id: 'col2', header: 'จำนวน', field: 'qty', width: '0.8fr', align: 'center' },
              { id: 'col3', header: 'ราคา/หน่วย', field: 'price', width: '1.2fr', align: 'right' },
              { id: 'col4', header: 'ส่วนลด', field: 'discount', width: '1fr', align: 'right' },
              { id: 'col5', header: 'จำนวนเงิน', field: 'total', width: '1.5fr', align: 'right' },
            ],
            style: {
              headerBackground: '#1e40af',
              headerTextColor: '#ffffff',
              borderColor: '#cbd5e1',
              borderWidth: '0.5pt',
              cellPadding: '8pt',
              fontSize: 9,
              fillPattern: 'striped-rows',
              stripedColor1: '#f8fafc',
              stripedColor2: '#ffffff',
            },
          },

          // Summary Section
          {
            id: 'summary-box',
            type: 'summary-box',
            x: 110,
            y: 165,
            width: 70,
            height: 35,
            rows: [
              { label: 'ยอดรวม (Subtotal)', value: '{{invoice.subtotal}}', style: 'normal' },
              {
                label: 'ส่วนลด (Discount)',
                value: '{{invoice.discount_total}}',
                style: 'highlight',
              },
              { label: 'ภาษีมูลค่าเพิ่ม 7% (VAT)', value: '{{invoice.vat_amount}}', style: 'normal' },
              { label: 'ยอดเงินสุทธิ (TOTAL)', value: '{{invoice.total}}', style: 'total' },
            ],
          },

          // Terms and Conditions
          {
            id: 'terms',
            type: 'text',
            content:
              'TERMS & CONDITIONS\n\n1. Payment is due within 30 days.\n2. Payable to: Thai Tech Solutions\n3. Bank Transfer: K-Bank 123-4-56789-0',
            x: 0,
            y: 165,
            width: 100,
            height: 30,
            style: { fontSize: 8, color: '#475569', lineHeight: 1.4 },
            align: 'left',
          },
        ],
      },
    },
  ],
  variables: [
    {
      name: 'companyName',
      type: 'string',
      defaultValue: 'บริษัท ไทยเทค โซลูชั่นส์ จำกัด',
      description: 'ชื่อบริษัท',
    },
    { name: 'vatRate', type: 'number', defaultValue: 7, description: 'อัตราภาษีมูลค่าเพิ่ม (%)' },
  ],
  dataSchema: [
    {
      path: 'invoice.number',
      type: 'string',
      required: true,
      description: 'เลขที่ใบแจ้งหนี้',
      example: 'INV-2024-00142',
    },
    { path: 'invoice.date', type: 'date', required: true, description: 'วันที่ออกใบแจ้งหนี้' },
    { path: 'invoice.customer.name', type: 'string', required: true, description: 'ชื่อลูกค้า' },
    { path: 'invoice.customer.address', type: 'string', required: true, description: 'ที่อยู่ลูกค้า' },
    {
      path: 'invoice.customer.tax_id',
      type: 'string',
      required: false,
      description: 'เลขประจำตัวผู้เสียภาษี',
    },
    { path: 'invoice.items', type: 'array', required: true, description: 'รายการสินค้า/บริการ' },
  ],
  metadata: {
    title: 'Multi-page Professional Invoice',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    author: 'TypstFlow System',
  },
};

// Sample data with MANY items to demonstrate multi-page
export const INVOICE_WITH_MANY_ITEMS_SAMPLE_DATA = {
  invoice: {
    number: 'INV-2024-00142',
    date: '2024-04-17',
    due_date: '2024-05-17',
    tax_type: 'VAT',
    vat_rate: 7,
    customer: {
      name: 'บริษัท ลูกค้าตัวอย่าง จำกัด',
      address: '456 ถนนพระราม 4 แขวงคลองเตยเหนือ เขตวัฒนา กรุงเทพฯ 10400',
      tax_id: '0105568234567',
      phone: '02-987-6543',
      email: 'accounting@customer.co.th',
    },
    // สร้างรายการสินค้าให้มากๆ เพื่อให้เกิน 1 หน้า!
    items: [
      {
        description: 'บริการพัฒนาซอฟต์แวร์ระบบ ERP',
        qty: 1,
        unit: 'โครงการ',
        price: 150000,
        discount: 0,
        total: 150000,
      },
      {
        description: 'บริการดูแลรักษาระบบ (เดือนมกราคม)',
        qty: 1,
        unit: 'เดือน',
        price: 8000,
        discount: 0,
        total: 8000,
      },
      {
        description: 'บริการดูแลรักษาระบบ (เดือนกุมภาพันธ์)',
        qty: 1,
        unit: 'เดือน',
        price: 8000,
        discount: 0,
        total: 8000,
      },
      {
        description: 'บริการดูแลรักษาระบบ (เดือนมีนาคม)',
        qty: 1,
        unit: 'เดือน',
        price: 8000,
        discount: 0,
        total: 8000,
      },
      {
        description: 'บริการดูแลรักษาระบบ (เดือนเมษายน)',
        qty: 1,
        unit: 'เดือน',
        price: 8000,
        discount: 0,
        total: 8000,
      },
      {
        description: 'บริการดูแลรักษาระบบ (เดือนพฤษภาคม)',
        qty: 1,
        unit: 'เดือน',
        price: 8000,
        discount: 0,
        total: 8000,
      },
      {
        description: 'บริการดูแลรักษาระบบ (เดือนมิถุนายน)',
        qty: 1,
        unit: 'เดือน',
        price: 8000,
        discount: 0,
        total: 8000,
      },
      {
        description: 'License ซอฟต์แวร์ Database (1 ปี)',
        qty: 1,
        unit: 'ใบอนุญาต',
        price: 25000,
        discount: 0,
        total: 25000,
      },
      {
        description: 'License ซอฟต์แวร์ Backup System (1 ปี)',
        qty: 1,
        unit: 'ใบอนุญาต',
        price: 18000,
        discount: 0,
        total: 18000,
      },
      {
        description: 'Cloud Server Storage (5 TB)',
        qty: 12,
        unit: 'เดือน',
        price: 1500,
        discount: 0,
        total: 18000,
      },
      {
        description: 'Cloud Server Storage (10 TB)',
        qty: 12,
        unit: 'เดือน',
        price: 2500,
        discount: 0,
        total: 30000,
      },
      {
        description: 'บริการติดตั้ง Server ใหม่',
        qty: 1,
        unit: 'ครั้ง',
        price: 5000,
        discount: 0,
        total: 5000,
      },
      {
        description: 'บริการ Migration Data',
        qty: 1,
        unit: 'ครั้ง',
        price: 12000,
        discount: 0,
        total: 12000,
      },
      {
        description: 'บริการ Train ผู้ใช้งานระบบ',
        qty: 2,
        unit: 'วัน',
        price: 8000,
        discount: 0,
        total: 16000,
      },
      {
        description: 'บริการ Consult ระบบ',
        qty: 5,
        unit: 'ชั่วโมง',
        price: 1500,
        discount: 0,
        total: 7500,
      },
      {
        description: 'ค่าธรรมเนียม Service Fee',
        qty: 1,
        unit: 'ครั้ง',
        price: 3000,
        discount: 0,
        total: 3000,
      },
      {
        description: 'อุปกรณ์ Network Switch 24 Port',
        qty: 2,
        unit: 'ตัว',
        price: 4500,
        discount: 500,
        total: 8000,
      },
      {
        description: 'สาย LAN Cat.6 (กล่องละ 30 เมตร)',
        qty: 5,
        unit: 'กล่อง',
        price: 1200,
        discount: 0,
        total: 6000,
      },
      {
        description: 'อุปกรณ์ Rack Mount 42U',
        qty: 1,
        unit: 'ตัว',
        price: 15000,
        discount: 0,
        total: 15000,
      },
      { description: 'ค่าจัดส่งทั่วประเทศ', qty: 1, unit: 'ครั้ง', price: 2000, discount: 0, total: 2000 },
      {
        description: 'ส่วนลดพิเศษสำหรับลูกค้ารายใหม่',
        qty: 1,
        unit: 'รายการ',
        price: 5000,
        discount: 5000,
        total: 0,
      },
    ],
    subtotal: 368500,
    discount_total: 5500,
    vat_amount: 25410,
    total: 388410,
    payment_terms: 'ชำระภายใน 30 วันนับจากวันที่รับใบแจ้งหนี้',
    notes: 'ขอบคุณที่ใช้บริการ หากมีข้อสงสัยประการใด กรุณาติดต่อเรา',
  },
  company: {
    name: 'บริษัท ไทยเทค โซลูชั่นส์ จำกัด',
    address: '123 ถนนสุขุมวิท แขวงคลองเตย เขตคลองเตย กรุงเทพฯ 10110',
    tax_id: '0105567123456',
    phone: '02-123-4567',
    email: 'accounting@thaitech.co.th',
    website: 'www.thaitech.co.th',
  },
};
