import type { LayoutSchema } from '../../types/schema';

export const TAX_INVOICE_TEMPLATE: LayoutSchema = {
  id: 'blue-sky-tax-invoice',
  name: 'Tax Invoice (Blue Sky)',
  version: '1.0.0',
  page: {
    size: 'A4',
    orientation: 'portrait',
    margin: { top: '10mm', bottom: '10mm', left: '15mm', right: '15mm' },
  },
  fonts: [{ family: 'Sarabun', role: 'body', size: 10, embedded: true }],
  zones: {
    header: {
      id: 'header',
      minHeight: '40mm',
      showOnFirstPageOnly: true,
      components: [
        {
          id: 'logo-text',
          type: 'text',
          content: 'BLUE SKY INDIA LIMITED',
          x: 15,
          y: 5,
          width: 120,
          height: 10,
          style: { fontSize: 24, fontWeight: 'bold', color: '#581c87' }, // Deep Purple
          align: 'left',
        },
        {
          id: 'gst-no',
          type: 'text',
          content: 'GST No. ASDF23486DD',
          x: 15,
          y: 15,
          width: 100,
          height: 5,
          style: { fontSize: 10, fontWeight: 'bold', color: '#581c87' },
          align: 'left',
        },
        {
          id: 'company-details',
          type: 'text',
          content:
            'B-126, Rear Side Basement Malviya Nagar New Delhi-110017\ne-mail : info@gmail.com, Ph. 011-3483465734, 123323487348\nState Name : Delhi, State Code : DL',
          x: 15,
          y: 20,
          width: 150,
          height: 15,
          style: { fontSize: 8.5, fontWeight: 'bold', color: '#000000', lineHeight: 1.3 },
          align: 'left',
        },
        // Tax Invoice Badge
        {
          id: 'tax-badge-bg',
          type: 'line',
          x: 150, // 15 (margin) + 180 (content) - 45 (width)
          y: 5,
          width: 45,
          height: 12,
          thickness: '12mm',
          color: '#9333ea',
        },
        {
          id: 'tax-badge-text',
          type: 'text',
          content: 'Tax Invoice',
          x: 150,
          y: 6.5, // Refined for vertical center in 12mm bar
          width: 45,
          height: 12,
          style: { fontSize: 13, color: '#ffffff', fontWeight: 'bold' },
          align: 'center',
        },
      ],
    },
    body: {
      id: 'body',
      minHeight: '220mm',
      components: [
        // Top Header Bar for Client Section
        {
          id: 'client-bar',
          type: 'line',
          x: 15,
          y: 0,
          width: 180,
          height: 6,
          thickness: '6mm',
          color: '#c084fc',
        }, // Light Purple
        {
          id: 'client-label',
          type: 'text',
          content: 'Client Name : {{invoice.customer.name}}',
          x: 17,
          y: 1, // Balanced within 6mm bar
          width: 100,
          height: 4,
          style: { fontSize: 9, fontWeight: 'bold', color: '#000000' },
          align: 'left',
        },
        {
          id: 'date-label',
          type: 'text',
          content: 'Date : {{invoice.date}}',
          x: 145,
          y: 1,
          width: 48,
          height: 4,
          style: { fontSize: 9, fontWeight: 'bold', color: '#000000' },
          align: 'right',
        },

        // Bordered Client Box
        {
          id: 'client-box-border',
          type: 'line',
          x: 15,
          y: 6,
          width: 180,
          height: 20,
          thickness: '0.2mm',
          color: '#000000',
        },
        {
          id: 'client-details',
          type: 'text',
          content: 'Address : {{invoice.customer.address}}\nGSTIN : {{invoice.customer.tax_id}}',
          x: 17,
          y: 7,
          width: 120,
          height: 18,
          style: { fontSize: 9, fontWeight: 'bold', color: '#000000', lineHeight: 1.4 },
          align: 'left',
        },
        {
          id: 'invoice-no',
          type: 'text',
          content: 'Invoice No : {{invoice.number}}',
          x: 145,
          y: 7,
          width: 48,
          height: 5,
          style: { fontSize: 9, fontWeight: 'bold', color: '#000000' },
          align: 'right',
        },

        // Delivery Address Sub-section
        {
          id: 'delivery-label',
          type: 'text',
          content: 'Delivery Address:',
          x: 17,
          y: 28,
          width: 50,
          height: 4,
          style: { fontSize: 9, fontWeight: 'bold', color: '#000000', underline: true },
          align: 'left',
        },
        {
          id: 'delivery-details',
          type: 'text',
          content:
            'Client Name : {{invoice.customer.name}}\nAddress : {{invoice.customer.address}}\nGSTIN : {{invoice.customer.tax_id}}',
          x: 17,
          y: 33,
          width: 120,
          height: 18,
          style: { fontSize: 9, fontWeight: 'bold', color: '#000000', lineHeight: 1.4 },
          align: 'left',
        },
        {
          id: 'state-details',
          type: 'text',
          content: 'State Name: Delhi\n\nState Code: DL',
          x: 135,
          y: 28,
          width: 58,
          height: 15,
          style: { fontSize: 9, color: '#000000' },
          align: 'right',
        },

        // Table
        {
          id: 'tax-table',
          type: 'table',
          dataSource: '{{invoice.items}}',
          x: 15,
          y: 55,
          width: 180,
          height: 120,
          showHeader: true,
          repeatHeaderOnPage: true,
          columns: [
            { id: 'sno', header: 'S.No', field: 'index', width: '0.4fr', align: 'center' },
            {
              id: 'desc',
              header: 'Description',
              field: 'description',
              width: '3fr',
              align: 'left',
            },
            { id: 'hsn', header: 'HSN Code', field: 'hsn', width: '1fr', align: 'center' },
            { id: 'qty', header: 'Qty', field: 'qty', width: '0.6fr', align: 'center' },
            { id: 'rate', header: 'Rate', field: 'price', width: '0.8fr', align: 'right' },
            { id: 'amt', header: 'Amount', field: 'total', width: '1.2fr', align: 'right' },
          ],
          style: {
            headerBackground: '#c084fc',
            headerTextColor: '#000000',
            borderColor: '#000000',
            borderWidth: '0.5pt',
            cellPadding: '6pt',
            fontSize: 9,
          },
          footerRows: [
            {
              id: 'footer-total-value',
              type: 'footer',
              cells: [
                {
                  id: 'lbl-total',
                  content: 'Total Value',
                  colspan: 5,
                  align: 'right',
                  fill: '#c084fc',
                  style: { fontWeight: 'bold' },
                },
                {
                  id: 'val-total',
                  content: '{{invoice.subtotal}}',
                  align: 'right',
                  fill: '#c084fc',
                  style: { fontWeight: 'bold' },
                },
              ],
            },
            {
              id: 'footer-cgst',
              type: 'footer',
              cells: [
                { id: 'empty1', content: '', colspan: 3 },
                {
                  id: 'lbl-cgst',
                  content: 'Add : CGST',
                  colspan: 2,
                  align: 'right',
                  style: { fontWeight: 'bold' },
                },
                { id: 'val-cgst', content: '14%', align: 'center', style: { fontWeight: 'bold' } }, // Following the image style of 14%
              ],
            },
            {
              id: 'footer-sgst',
              type: 'footer',
              cells: [
                { id: 'empty2', content: '', colspan: 3 },
                {
                  id: 'lbl-sgst',
                  content: 'Add : SGST',
                  colspan: 2,
                  align: 'right',
                  style: { fontWeight: 'bold' },
                },
                { id: 'val-sgst', content: '14%', align: 'center', style: { fontWeight: 'bold' } },
              ],
            },
            {
              id: 'footer-grand-total',
              type: 'footer',
              cells: [
                {
                  id: 'lbl-grand',
                  content: 'Grand Total',
                  colspan: 5,
                  align: 'right',
                  fill: '#c084fc',
                  style: { fontWeight: 'bold' },
                },
                {
                  id: 'val-grand',
                  content: '{{invoice.total}}',
                  align: 'right',
                  fill: '#c084fc',
                  style: { fontWeight: 'bold' },
                },
              ],
            },
          ],
          vlines: [
            { id: 'v1', x: 1, stroke: '0.5pt + black' },
            { id: 'v2', x: 2, stroke: '0.5pt + black' },
            { id: 'v3', x: 3, stroke: '0.5pt + black' },
            { id: 'v4', x: 4, stroke: '0.5pt + black' },
            { id: 'v5', x: 5, stroke: '0.5pt + black' },
          ],
        },

        {
          id: 'amt-words',
          type: 'text',
          content: 'Amount in Words: _______________________',
          x: 15,
          y: 215,
          width: 100,
          height: 5,
          style: { fontSize: 10, fontWeight: 'bold' },
          align: 'left',
        },
      ],
    },
    footer: {
      id: 'footer',
      minHeight: '30mm',
      showOnLastPageOnly: true,
      components: [
        {
          id: 'for-company',
          type: 'text',
          content: 'For BLUE SKY INDIA LIMITED',
          x: 115,
          y: 5,
          width: 80,
          height: 5,
          style: { fontSize: 9, fontWeight: 'bold' },
          align: 'right',
        },
        {
          id: 'signature',
          type: 'text',
          content: 'Authorised Signature',
          x: 115,
          y: 22,
          width: 80,
          height: 5,
          style: { fontSize: 10, fontWeight: 'bold' },
          align: 'right',
        },
      ],
    },
  },
  variables: [],
  dataSchema: [],
  metadata: {
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    author: 'Antigravity Designer',
  },
};

export const TAX_INVOICE_SAMPLE_DATA = {
  invoice: {
    number: '76/2017-18',
    date: '25-10-2017',
    customer: {
      name: 'TECHGURUPLUS',
      address: 'H-195, Sarita Vihar, New Delhi 110076',
      tax_id: '07PDUJS4678K1Z4',
    },
    items: [
      { index: 1, description: 'Service Item 1', hsn: '998311', qty: 1, price: 1000, total: 1000 },
      { index: 2, description: 'Service Item 2', hsn: '998312', qty: 2, price: 500, total: 1000 },
    ],
    subtotal: 2000,
    cgst: 280,
    sgst: 280,
    total: 2560,
  },
};
